version: "3.9"
services:
    nextjs:
        build: ./client
        volumes:
            - ./client/build:/usr/app/build
            - ./client/public:/usr/app/public
    nginx:
        build: ./nginx
        ports:
            - 8000:80
    db:
        build: ./db
        environment:
            MYSQL_USER: server
            MYSQL_PASSWORD: hello
            MYSQL_ROOT_PASSWORD: hello
            MYSQL_DATABASE: waybill_cost
    go:
        build: ./go
        depends_on:
            - db
        environment:
            PORT: ":8000"
            RAJAONGKIRKEY: "553c7982c1e8205443b4ad8d584e399e"
            DSN: "server:hello@tcp(db:3306)/waybill_cost?charset=utf8mb4&parseTime=True&loc=Local"
        ports:
            - 5000:8000
