version: "3.9"
services:
    nextjs:
        build: ./client
    nginx:
        build: ./nginx
        ports:
            - 8000:80
    # go:
    #     build: ./go
    # db:
    #     build: ./db
    #     environment:
    #         MYSQL_USER: server
    #         MYSQL_PASSWORD: hello
    #         MYSQL_ROOT_PASSWORD: hello
    #         MYSQL_DATABASE: waybill_cost