name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node js version
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Building
        run: |
          node -v
          yarn -v
          yarn install
          yarn build
          ls -la