name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node js version
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Building
        run: |
          node -v
          yarn -v
          ls -la
          cd client
          yarn install
          yarn build
          ls -la
          ls -la build

      - name: Upload artiface
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-build
          path: build